line-length = 120

[lint]
# add rules for isort, pandas, variable naming, code complexity, bugbear, builtin collision, commas, comprehensions, errmsg, import name convention, logging format, return, simplify, tidy imports, unused arguments, pathlib, pylint, performance, refurb (experimental), logging, ruff rules, numpy 2 deprecation
# ERA for commented code
select = ["F", "E", "W", "I", "PD", "N", "C90", "B", "A", "C4", "EM", "ICN", "G", "RET", "SIM", "TID", "ARG", "PTH", "PL", "PERF", "LOG", "RUF", "NPY201"]
# ignore lambda assignment rule, unused loop variables, open vs pathlib.open, capital letter variable names, Unnecessary else after return, import sorting, uppercase import names, local * imports, no detection of unused variables from * imports, unnecessary assignment before return, Require strict in zip, Unnecessary List comprehension
ignore = ["E731", "B007", "PTH123", "N806", "RET505", "I001", "N812", "F403", "F405", "RET504", "B905",  "C419"]
pycodestyle.max-line-length = 120  # E501: reports lines that exceed the length of 120.
exclude = ['small_world_propensity.py', 'neurodata.py']

[format]
quote-style = "single"
